language: generic 
sudo: required
services:
    -docker

before_install:
    - docker build -t wilsonkaya/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true wilsonkaya/react-test npm test

after_success:
    - docker build -t wilsonkaya/multi-client ./client
    - docker build -t wilsonkaya/multi-nginx ./nginx
    - docker build -t wilsonkaya/multi-server ./server
    - docker build -t wilsonkaya/multi-worker ./worker    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push wilsonkaya/multi-client
    - docker push wilsonkaya/multi-nginx
    - docker push wilsonkaya/multi-server
    - docker push wilsonkaya/multi-worker
    