language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t fatihkaya2/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true fatihkaya2/react-test npm test

after_success:
    - docker build -t fatihkaya2/multi-client ./client
    - docker build -t fatihkaya2/multi-nginx ./nginx
    - docker build -t fatihkaya2/multi-server ./server
    - docker build -t fatihkaya2/multi-worker ./worker    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
    - docker push fatihkaya2/multi-client
    - docker push fatihkaya2/multi-nginx
    - docker push fatihkaya2/multi-server
    - docker push fatihkaya2/multi-worker
    