language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t fatihkaya2/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true fatihkaya2/react-test npm test

after_success:
    - docker build -t fatihkaya2/multi-client ./client
    - docker build -t fatihkaya2/multi-nginx ./nginx
    - docker build -t fatihkaya2/multi-server ./server
    - docker build -t fatihkaya2/multi-worker ./worker    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push fatihkaya2/multi-client
    - docker push fatihkaya2/multi-nginx
    - docker push fatihkaya2/multi-server
    - docker push fatihkaya2/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-820509588610
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY